// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://augjsnaxjaiyltgocmft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1Z2pzbmF4amFpeWx0Z29jbWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTI3MzgsImV4cCI6MjA3NDQ2ODczOH0.ftyQ54p9Vs-DL0RSjOmkjeSUKBsTGu5W-nZj5PafNEs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});